### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by DariBer** [matt-FFFFFF/hassio-addon-repository#1]
When pressing open Web UI from the add-on TeslaMate I get an 502: Bad Gateway, so I had to add port (4000) in the Network section and then I can access the TeslaMate by going to http://addresstomyhass:4000/ 

I get the same problem with the 502: Bad Gateway, when I enable show in sidebar

**Comment by matt-FFFFFF** [comment]
Hi,

We cannot yet support ingress due to lack of URI path support in Teslamate - please read the README.md for the addon:
https://github.com/matt-FFFFFF/hassio-addon-repository/blob/master/teslamate/README.md

Also see adriankumpf/teslamate#494

I should disable ingress support, and with it the ```Web UI``` link in the config.json

**Comment by matt-FFFFFF** [comment]
Links removed in v0.0.7 - 3c0c7b2
